version: '3'
services:
  base:
    env_file:
      - .docker_env
    image: node:16.20.2-bookworm
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: npm run dev
  install:
    extends:
      base
    command: /bin/sh -c "npm install --no-save --unsafe-perm"
