# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: corepack enable pnpm
    - run: pnpm i --frozen-lockfile
    #- run: npm run lint:check
    #- run: npm run test:unit
    #- run: npm run test-server &
    #- run: npm run test
    - run: pnpm run build
